# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.5

# configure notifications (email, IRC, campfire etc)
notifications:
  slack: hodorhodor:KCZ7JI6kYJr7cZvEAgeA0tmy